name: PR Build

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - name: Print CLI version
        run: |
          rm -rf ktlint
          curl -JLO https://github.com/pinterest/ktlint/releases/download/0.48.1/ktlint
          chmod +x ktlint
          ./ktlint --version
